# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(default=datetime.datetime(2016, 3, 6, 13, 48, 3, 132126, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
