# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_courses_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='year',
            field=models.ForeignKey(default=datetime.datetime(2016, 3, 6, 18, 28, 36, 346995, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='app.Year'),
            preserve_default=False,
        ),
    ]
