# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subjects_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='year',
        ),
    ]
