# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_subjects_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Year'),
        ),
    ]
