# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_school_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='year',
        ),
    ]
