# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160306_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
