# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 05:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160308_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 9, 5, 56, 4, 761330)),
        ),
    ]
